### ISSUE TITLE
problem with installing PDL::Parallel::threads

### ISSUE THREAD

**Issue by KamilSJaron** [swainechen/lacer#2]
Hello, I know it's not technically your problem, but one of your dependencies (`PDL::Parallel::threads`) have problem in build script and it seems that developers do not really care. The problem is described in their [issue tracker](https://github.com/run4flat/PDL-Parallel-threads/issues/1) together with a solution that have worked for me.

I suggest to add this info and link to your README, because today I spend quite lot of time before I resolved the issue.

**Comment by swainechen** [comment]
Oh. Sorry just saw this. Looks like it is solved, I found this out myself a while back. Thanks for documenting!

**Comment by run4flat** [comment]
PDL::Parallel::threads author here. The module has finally been updated and version bumped to v0.04, just uploaded to CPAN. It now compiles on my machine. I expect it'll compile everywhere, though I'll have to wait for reports from CPAN Testers to be sure. Sorry for the long, long delay! I didn't know anybody used my module for anything serious! I'll keep a closer eye on it moving forward.

**Comment by KamilSJaron** [comment]
Sorry for my wording @run4flat, I simply wanted to say that the problem is reported, has a solution, but it's not fixed. The lack of care comment was just stupid, thank you for your open source contributions!

**Comment by run4flat** [comment]
@KamilSJaron no worries. Thanks for going through the effort of linking this issue on this project to mine, or I never would have known about the dependency!

**Comment by swainechen** [comment]
Hey both, thanks for chasing this down. @KamilSJaron sorry this cost you so much time, and I'll update my docs on this side appropriately. @run4flat thanks for writing the module, I definitely found it useful - it was exactly what I needed, and on first implementation way back when it gave me a >3x speed improvement!
